// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: encryption_message.proto

package encryption

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GRpcService_EncryptionProcess_FullMethodName = "/encryption.GRpcService/encryptionProcess"
)

// GRpcServiceClient is the client API for GRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRpcServiceClient interface {
	EncryptionProcess(ctx context.Context, in *EncryptionProcessRequest, opts ...grpc.CallOption) (*EncryptionProcessResponse, error)
}

type gRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGRpcServiceClient(cc grpc.ClientConnInterface) GRpcServiceClient {
	return &gRpcServiceClient{cc}
}

func (c *gRpcServiceClient) EncryptionProcess(ctx context.Context, in *EncryptionProcessRequest, opts ...grpc.CallOption) (*EncryptionProcessResponse, error) {
	out := new(EncryptionProcessResponse)
	err := c.cc.Invoke(ctx, GRpcService_EncryptionProcess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRpcServiceServer is the server API for GRpcService service.
// All implementations must embed UnimplementedGRpcServiceServer
// for forward compatibility
type GRpcServiceServer interface {
	EncryptionProcess(context.Context, *EncryptionProcessRequest) (*EncryptionProcessResponse, error)
	mustEmbedUnimplementedGRpcServiceServer()
}

// UnimplementedGRpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGRpcServiceServer struct {
}

func (UnimplementedGRpcServiceServer) EncryptionProcess(context.Context, *EncryptionProcessRequest) (*EncryptionProcessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EncryptionProcess not implemented")
}
func (UnimplementedGRpcServiceServer) mustEmbedUnimplementedGRpcServiceServer() {}

// UnsafeGRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRpcServiceServer will
// result in compilation errors.
type UnsafeGRpcServiceServer interface {
	mustEmbedUnimplementedGRpcServiceServer()
}

func RegisterGRpcServiceServer(s grpc.ServiceRegistrar, srv GRpcServiceServer) {
	s.RegisterService(&GRpcService_ServiceDesc, srv)
}

func _GRpcService_EncryptionProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptionProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRpcServiceServer).EncryptionProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GRpcService_EncryptionProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRpcServiceServer).EncryptionProcess(ctx, req.(*EncryptionProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRpcService_ServiceDesc is the grpc.ServiceDesc for GRpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "encryption.GRpcService",
	HandlerType: (*GRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "encryptionProcess",
			Handler:    _GRpcService_EncryptionProcess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "encryption_message.proto",
}
