[[DeviceList]]
  Name = "default-socket-device"
  ProfileName = "Socket-Device-Profile"
  Description = "Socket device get student learning behavior"
  Labels = [ "socket" ]
  [DeviceList.Protocols]
  [DeviceList.Protocols.socket]
    deviceIP = "127.0.0.1"
  [DeviceList.Protocols.deviceDataLabel]
    student_id = "S001"
    task_id = "0"
  [[DeviceList.AutoEvents]]
    Interval = "1s"
    OnChange = false
    SourceName = "FacialAndEEG"
  [[DeviceList.AutoEvents]]
    Interval = "1s"
    OnChange = false
    SourceName = "KeyboardAndMouse"